import { APP_URLS } from "@/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const links = [
    {
      href: APP_URLS.home,
      name: "home",
    },
    {
      href: APP_URLS.movies,
      name: "movies",
    },
    {
      href: APP_URLS.characters,
      name: "characters",
    },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="hidden sm:grid sm:place-items-center">
          <nav className="flex gap-4">
            {links.map((link) => (
              <Link
                key={`app-link-${link.name}`}
                href={link.href}
                className="capitalize"
              >
                {link.name}
              </Link>
            ))}
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
